spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: config-demo
              uri: lb://config-server
              predicates:
                - Path=/config/**
              filters:
                - StripPrefix=1
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**