softlaunch:
  welcome: "Hello from Config Server"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      softlaunch:
        jwt:
          secret: AqiH/i6xsQ9p4WXceT2MFqXhOwvfjX3pjK7cSUYjYF0=