server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/match_db
    username: softlaunch
    password: softlaunch
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

softlaunch:
  swipes:
    daily-limit: 3