package com.softlaunch.user.model;

public enum Interest {
    TRAVEL, MUSIC, MOVIES, GYM, YOGA, CRICKET, FOOTBALL, GAMING,
    COOKING, FOODIE, COFFEE, READING, PHOTOGRAPHY, DANCING, HIKING,
    ART, TECH, FASHION, PETS, ANIME, STANDUP_COMEDY, PARTYING,
    MEDITATION, VOLUNTEERING
}