services:
  user-db:
    image: postgres:17
    container_name: softlaunch-user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: softlaunch
      POSTGRES_PASSWORD: softlaunch
    ports:
      - "5433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  match-db:
    image: postgres:17
    container_name: softlaunch-match-db
    environment:
      POSTGRES_DB: match_db
      POSTGRES_USER: softlaunch
      POSTGRES_PASSWORD: softlaunch
    ports:
      - "5434:5432"
    volumes:
      - match-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: softlaunch-redis
    ports:
      - "6379:6379"

volumes:
  user-db-data:
  match-db-data: